<h1>Hello</h1>
<button class="example-button-1 example-button-2" type="button"><span>Button</span></button>
<button class="example-button-1 example-button-2 :hover" type="button"><span>Hover</span></button>
<button class="example-button-1 example-button-2 :active" type="button"><span>Active</span></button>
<button class="example-button-1 example-button-2" type="button" disabled><span>Disabled</span></button>